"""The demo dataset, and the translation from a browser's fixtures to rows.

Half of these test the loader; half test the *file*. The second half matters
more than it looks: the fixtures are generated by a script in another
repository, and a bad regeneration would otherwise be discovered as a foreign
key violation in a container at three in the afternoon.
"""

from __future__ import annotations

import uuid
from collections import Counter

from app.seed.loader import SEED_NAMESPACE, load_fixtures, stable_id
from app.seed.loader import _order_nodes  # noqa: PLC2701 - ordering is worth pinning


# -- deterministic identifiers --------------------------------------------


def test_the_same_string_always_becomes_the_same_uuid() -> None:
    """What makes seeding idempotent and cross-references survive translation."""
    assert stable_id("user", "usr_0001") == stable_id("user", "usr_0001")


def test_the_kind_keeps_namespaces_apart() -> None:
    """A person and an account sharing a string id must not collide."""
    assert stable_id("user", "x_1") != stable_id("relation", "x_1")


def test_the_namespace_is_pinned() -> None:
    """Changing it would orphan every row ever seeded, so it is a constant."""
    assert SEED_NAMESPACE == uuid.UUID("6f9619ff-8b86-d011-b42d-00c04fc964ff")


def test_ids_are_valid_uuids_of_the_expected_version() -> None:
    assert stable_id("user", "usr_0001").version == 5


# -- parent-before-child ordering -----------------------------------------


def test_nodes_are_ordered_so_parents_come_first() -> None:
    scrambled = [
        {"id": "leaf", "parent_id": "mid"},
        {"id": "mid", "parent_id": "root"},
        {"id": "root", "parent_id": None},
    ]

    order = [n["id"] for n in _order_nodes(scrambled)]

    assert order.index("root") < order.index("mid") < order.index("leaf")


def test_a_cycle_does_not_hang_the_loader() -> None:
    """It gives up and lets the foreign key complain, rather than looping."""
    cyclic = [{"id": "a", "parent_id": "b"}, {"id": "b", "parent_id": "a"}]

    assert len(_order_nodes(cyclic)) == 2


# -- the fixture file itself ----------------------------------------------


def test_the_fixtures_load_and_carry_every_table() -> None:
    data = load_fixtures()

    assert set(data) >= {
        "people",
        "connected_accounts",
        "messages",
        "person_notes",
        "org_nodes",
        "ingestion_runs",
    }
    assert data["people"], "an empty dataset would seed a stack with nothing in it"


def test_no_table_contains_a_duplicate_id() -> None:
    data = load_fixtures()

    for table, key in (
        ("people", "id"),
        ("connected_accounts", "id"),
        ("messages", "id"),
        ("org_nodes", "id"),
        ("ingestion_runs", "run_id"),
    ):
        duplicates = [i for i, n in Counter(r[key] for r in data[table]).items() if n > 1]
        assert not duplicates, f"{table} has duplicate ids: {duplicates}"


def test_every_reference_points_at_something_that_exists() -> None:
    """The check that turns a bad regeneration into a failed test run."""
    data = load_fixtures()
    people = {p["id"] for p in data["people"]}
    accounts = {a["id"] for a in data["connected_accounts"]}
    nodes = {n["id"] for n in data["org_nodes"]}

    dangling: list[str] = []
    for account in data["connected_accounts"]:
        if account["user_id"] and account["user_id"] not in people:
            dangling.append(f"account {account['id']} -> user {account['user_id']}")
    for message in data["messages"]:
        if message["sender_user_id"] and message["sender_user_id"] not in people:
            dangling.append(f"message {message['id']} -> user {message['sender_user_id']}")
        if message["sender_relation_id"] and message["sender_relation_id"] not in accounts:
            dangling.append(
                f"message {message['id']} -> account {message['sender_relation_id']}"
            )
    for note in data["person_notes"]:
        if note["user_id"] not in people:
            dangling.append(f"note {note['id']} -> user {note['user_id']}")
    for node in data["org_nodes"]:
        if node["parent_id"] and node["parent_id"] not in nodes:
            dangling.append(f"node {node['id']} -> parent {node['parent_id']}")
        for member in node["member_ids"]:
            if member not in people:
                dangling.append(f"node {node['id']} -> member {member}")

    assert not dangling, "fixtures reference rows that do not exist:\n  " + "\n  ".join(
        dangling
    )


def test_nobody_is_filed_into_two_departments() -> None:
    """The database enforces this; the fixtures have to respect it or fail to load."""
    data = load_fixtures()
    memberships = [m for node in data["org_nodes"] for m in node["member_ids"]]

    assert len(memberships) == len(set(memberships))


def test_the_dataset_exercises_the_states_the_console_can_show() -> None:
    """A seed that only covers the happy path hides half the console's screens."""
    data = load_fixtures()

    assert any(a["user_id"] is None for a in data["connected_accounts"]), "unlinked accounts"
    assert any(m["sender_user_id"] is None for m in data["messages"]), "orphaned messages"
    assert any(m.get("kind") == "commit" for m in data["messages"]), "commits"
    assert any(m.get("commit") for m in data["messages"]), "commit detail"
    assert len({m["filter_category"] for m in data["messages"]}) > 1, "filter categories"
    assert any(n["parent_id"] for n in data["org_nodes"]), "a nested department"
